baseurl: /jekyll_demo
baseurl: /jekyll_demo
name: "Blog of ChengYiFan"
description: "Web Front-End Blog by ChengYiFan"

url: "https://chengyifan.github.com/jekyll_demo/"

timezone: Asia/Beijing

paginate: 20

highlighter: pygments

markdown: rdiscount
permalink: pretty