baseurl: /blog
name: "Cynthia's Blog"
description: "一个PD&FE的成长空间"

url: "https://chengyifan.github.io/blog/"

timezone: Asia/Beijing

paginate: 1
paginate_path: "blog/page:num"

highlighter: pygments

markdown: rdiscount
permalink: pretty